config/routes.rb
Bakery::Application.routes.draw do
  devise_for :users

  resources :recipes, :only => [:index, :show, :new, :create, :update, :destroy] do
    resources :ingredients, :only => [:index, :new, :create]
  end
  resources :ingredients, :only => [:show, :edit, :update, :destroy]
  resource :site, :only => [:show] do
    resource :config, :only => [:show], :controller => "site/config"
    resource :mail, :only => [:create, :new, :show], :controller => "site/mails"
    resource :error, :only => [:create, :new, :show], :controller => "site/errors"
  end

  root :to => "home#show"

end

app/controllers/site/config_controller.rb
class Site::ConfigController < ApplicationController
  before_filter {authorize! :manage, :site}
end

app/controllers/site/errors_controller.rb
class Site::ErrorsController < ApplicationController
  before_filter :authenticate_user!
  before_filter {authorize! :manage, :site}
  
  def show
    redirect_to(new_site_errors_path)
  end
  
  def new
    respond_to do |format|
      format.html
    end
  end

  def create
    raise "This is an intentionally generated error."
  end
end

app/controllers/site/mails_controller.rb
class Site::MailsController < ApplicationController
  before_filter :authenticate_user!
  before_filter {authorize! :manage, :site}
  
  def show
    redirect_to(new_site_mail_path)
  end
  
  def new
    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @mail }
    end
  end

  def create
    respond_to do |format|
      begin
        SiteMailer.test_email.deliver 
      rescue Exception => ex
        logger.error(ex)
        flash[:notice] = "Error: " + ex.message
        format.html { render :action => "new" }
      else
        format.html { redirect_to(new_site_mail_path, :notice => 'Mail was successfully created.') }
      end
    end
  end
end

app/controllers/sites_controller.rb
class SitesController < ApplicationController
  before_filter :authenticate_user!
  before_filter {authorize! :manage, :site}
  
  def show
   
    respond_to do |format|
      format.html
    end
  end
end

app/helpers/site/config_helper.rb
module Site::ConfigHelper
end

app/helpers/site/errors_helper.rb
module Site::ErrorsHelper
end

app/helpers/site/mails_helper.rb
module Site::MailsHelper
end

app/helpers/sites_helper.rb
module SitesHelper
end

app/views/site/config/_section.haml
%h3 #{name}
%ul
  - hash = hash.sort {|a,b | a.to_s.downcase <=> b.to_s.downcase  }
  - hash.each do |key, value|
    %li
      - if value.respond_to? :each_pair
        = render :partial => "section", :locals => {:name => key, :hash => value }
      - else
        <span class="key">#{key.to_s}</span> = <span class="value">#{value.to_s}</span>

app/views/site/config/show.html.haml
- title "Configuration"
.site
  .configuration
    .app_config
      %h2 Application Configuration / Environment Variables
      = render :partial => "section", :locals => {:name => "All", :hash => APP_CONFIG }
    .navigation
      = link_to "Back to Site Admin", site_path