config/routes.rb
Bakery::Application.routes.draw do
  devise_for :users

  resources :recipes, :only => [:index, :show, :new, :create, :update, :destroy] do
    resources :ingredients, :only => [:index, :new, :create]
  end
  resources :ingredients, :only => [:show, :edit, :update, :destroy]
  resource :site, :only => [:show] do
    resource :config, :only => [:show], :controller => "site/config"
    resource :mail, :only => [:create, :new, :show], :controller => "site/mails"
    resource :error, :only => [:create, :new, :show], :controller => "site/errors"
  end

  root :to => "home#show"

end

app/models/recipe.rb
class Recipe < ActiveRecord::Base
  has_many :ingredients, :dependent => :destroy
  accepts_nested_attributes_for :ingredients, :reject_if => lambda { |a| a[:amount].blank? }, :allow_destroy => true
  attr_accessible :name, :yield, :yield_size, :yield_string, :ingredients_attributes, :user
  belongs_to :user
  has_friendly_id :name, :use_slug => true
  validates_presence_of :name
  before_validation :push_user_to_ingredients
  
  def yield_string
    "%.1d" % self.yield
  end
  
  def yield_string=(value)
    self.yield = Float(value)
  end
  
  def total_yield
    if !yield_size.nil?
      begin
        Recipe.total_yield(self.yield, self.yield_size)
      rescue ArgumentError
        self.yield    
      end
    else
      self.yield
    end
  end
  
  def self.total_yield(yield_, yield_size)
    return yield_size.unit * yield_
  end
  
  def scale(new_yield = nil, new_yield_size = nil)
    new_yield ||= self.yield
    new_yield_size ||= self.yield_size
    
    yield_size = new_yield_size
    
    if new_yield_size.nil?
      scaling_factor = Float(new_yield) / self.yield
    else
      scaling_factor = Recipe.total_yield(new_yield, new_yield_size) / self.total_yield
    end
    
    self.ingredients.each { |ingredient|      
      ingredient.scale(scaling_factor)
    }
    self.yield = new_yield
    self.yield_size = new_yield_size

    return self
  end
  
  def cost
    return ingredients.inject(0) do |total, ingredient| 
      return nil if total == nil 
      return nil if ingredient.cost == nil 
      total + ingredient.cost
    end
  end
  
  def unit_cost
    total_cost = cost
    return nil if total_cost == nil
    return nil unless self.yield
    return total_cost / self.yield
  end
  
  def push_user_to_ingredients()
    ingredients.each do |ingredient|
       ingredient.food.user ||= user if ingredient.food
    end
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_filter :authenticate_user!
  
  def index
    @recipes = current_user.recipes
  end
  
  def show
    @recipe = Recipe.find(params[:id])
    recipe_yield = params[:yield]
    unless recipe_yield.blank? 
      if params[:yield_size].blank?
        flash[:error] = "How big are your new serving sizes? We need to know before we can show you the recipe."
      elsif
        @recipe = @recipe.scale(recipe_yield, params[:yield_size])
        @scaled = true
      end
    end
  end
  
  def new
    @recipe = Recipe.new
  end
  
  def create
    @recipe = Recipe.new(params[:recipe])
    @recipe.user = current_user
    if @recipe.save
      flash[:notice] = "Successfully created recipe."
      redirect_to @recipe
    else
      render :action => 'new'
    end
  end
  
  def update
    @recipe = Recipe.find(params[:id])
    if params[:scale_action] == "scale" 
      redirect_to recipe_path(@recipe, params[:scale])
    elsif params[:scale_action] == "reset" 
      redirect_to @recipe
    else
      if params[:save_action] == "copy"
        params[:recipe][:name] = "#{params[:recipe][:name]} (#{params[:scale][:yield]}@#{params[:scale][:yield_size]})"
        create
      else
        if @recipe.update_attributes(params[:recipe])
          @recipe = Recipe.find(@recipe.id)
          flash[:notice] = "Successfully updated recipe."
          redirect_to @recipe
        else
          render :action => 'show'
        end
      end
    end
  end
  
  def destroy
    @recipe = Recipe.find(params[:id])
    @recipe.destroy
    flash[:notice] = "Successfully destroyed recipe."
    redirect_to recipes_url
  end
end

app/helpers/recipes_helper.rb
module RecipesHelper
  def current_user_foods_autocomplete
    current_user.foods.map {|food| food_autocomplete_properties(food) }
  end
  
  def food_autocomplete_properties(food)
    properties = food.autocomplete_properties
    properties[:purchase_amount] = na(properties[:purchase_amount])
    properties[:purchase_cost] = dollars(properties[:purchase_cost])
    properties
  end
end

app/views/recipes/_form.html.haml
:javascript
  $(document).ready(function(){
    var ingredients = #{current_user_foods_autocomplete.to_json};
    $('.ingredient .name input').autocomplete({
      source: ingredients,
       select: function(event, ui) {
         var ingredientElement = $(this).parent().parent();
         ingredientElement.find(".purchase_amount .value").text(ui.item.purchase_amount);
         ingredientElement.find(".purchase_cost .value").text(ui.item.purchase_cost);
       }
    });
  });

  = form_for @recipe, :html => { :class => "recipe_form"} do |f|
    = f.error_messages
    %p
      = f.label :name
    
    .yield
      %h2 Yield
      This recipe makes # {f.text_field :yield_string} servings. Each serving is # {f.text_field :yield_size} big.
    .ingredients
      %h2 Ingredients
      = f.fields_for :ingredients do |i|
        = render "ingredient_fields", :f => i
      = link_to_add_fields "Add Ingredient", f, :ingredients
    %p
      = f.submit

app/views/recipes/_ingredient_fields.html.haml
- new_ingredient ||= false
= i_form.fields_for :food do |f_form|
  %tr{:class=> ["ingredient", ( new_ingredient ? "new" : nil) ] }
    %td.description
      = i_form.text_field :amount, :class => "amount numeric"
      %span.name
        = new_ingredient ? f_form.text_field(:name) : f_form.object.name 
    %td.purchase
      :plain
      (#{ f_form.text_field :purchase_amount, :class => "amount numeric"} 
      @ 
      #{f_form.text_field :purchase_cost, :class => "cost numeric"}) =
    %td.cost
      = dollars(i_form.object.cost)
    %td.delete
      = i_form.check_box :_destroy

app/views/recipes/edit.html.haml
- title "Edit Recipe"

= render 'form'

%p
  = link_to "Show", recipe_path(@recipe)
  |
  = link_to "View All", recipes_path

app/views/recipes/index.html.haml
- title "Recipes"

%table
  %tr
    %th Name
  - for recipe in @recipes
    %tr
      %td= recipe.name
      %td= link_to 'Show', recipe
      %td= link_to 'Destroy', recipe, :confirm => 'Are you sure?', :method => :delete

%p= link_to "New Recipe", new_recipe_path

app/views/recipes/new.html.haml
- title "New Recipe"

= render 'form'

%p= link_to "Back to List", recipes_path

app/views/recipes/show.html.haml
.recipe_show_page.recipe_page
  :javascript
    $(document).ready(function(){
      $(".yield .servings input").clickToEdit({format: Bakery.na});
      $(".name h1 input").clickToEdit();
      $(".ingredients .ingredient:not(.new) .description .amount").clickToEdit({format: Bakery.na});
      $(".ingredients .ingredient .purchase input.amount").clickToEdit({format: Bakery.na});
      $(".ingredients .ingredient .purchase input.cost").clickToEdit({format: Bakery.dollars});

      var ingredients = #{current_user_foods_autocomplete.to_json};
      $('.ingredients .new .name input').autocomplete({
        source: ingredients,
         select: function(event, ui) {
           var ingredientElement = $(this).closest(".new");
           ingredientElement.find(".purchase .amount").val(ui.item.purchase_amount).change();
           ingredientElement.find(".purchase .cost").val(ui.item.purchase_cost).change();
         }
      });
    });

  = form_for @recipe, :html => { :class => "recipe_form"} do |r_form|
    .name
      %h1
        = r_form.text_field :name
    = r_form.error_messages

    .yield
      %h2
        Yield
      .servings    
        Makes #{r_form.text_field :yield_string, :class => "numeric"} servings
        of #{r_form.text_field :yield_size, :class => "numeric"} each.

      .scale
        I want to get <input name="scale[yield]" value="#{@recipe.yield_string}" class="numeric"/> servings of <input name="scale[yield_size]" value="#{@recipe.yield_size.try_unit}"  class="numeric"/> each. 
        %button{:type=>"submit", :name=>"scale_action", :value=>"scale"}
          Show me the recipe for this amount.
        - if @scaled
          %button{:type=>"submit", :name=>"scale_action", :value=>"reset"}
            Show me the original recipe amounts

    .ingredients
      %h2
        Ingredients:
      %table
        %tbody
          = r_form.fields_for :ingredients do |i_form|
            = render "ingredient_fields", :i_form => i_form
          = r_form.fields_for Ingredient.new do |i_form|
            - i_form.object.food = Food.new
            = render "ingredient_fields", :i_form => i_form, :new_ingredient => true
        %tfoot
          %tr.total
            %th.description
            %th.purchase
              Total Recipe Cost =
            %th.cost
              #{dollars(@recipe.cost)}
          %tr.unit_cost
            %th.description
            %th.purchase
              Cost per Serving =
            %th.cost
              #{dollars(@recipe.unit_cost)}
            %th.delete
    .save
      <button type="submit" name="save_action" value="commit">
      Update the recipe with these amounts
      </button>#{  @scaled ? ", " : "" }
      - if @scaled
        %button{:type=>"submit", :name=>"save_action", :value=>"copy"}
          Create a new copy of this scaled recipe    
      or
      #{link_to "Undo all changes", recipe_path(@recipe), :class=>"cancel"}

= link_to "Destroy", @recipe, :confirm => 'Are you sure?', :method => :delete
|
= link_to "View All", recipes_path