config/routes.rb
Bakery::Application.routes.draw do
  devise_for :users

  resources :recipes, :only => [:index, :show, :new, :create, :update, :destroy] do
    resources :ingredients, :only => [:index, :new, :create]
  end
  resources :ingredients, :only => [:show, :edit, :update, :destroy]
  resource :site, :only => [:show] do
    resource :config, :only => [:show], :controller => "site/config"
    resource :mail, :only => [:create, :new, :show], :controller => "site/mails"
    resource :error, :only => [:create, :new, :show], :controller => "site/errors"
  end

  root :to => "home#show"

end

app/models/ingredient.rb
require 'unit_validator'

class Ingredient < ActiveRecord::Base
  belongs_to :recipe
  belongs_to :food
  accepts_nested_attributes_for :food
  attr_accessible :amount, :sort_order, :food_attributes
  # TODO: Re-enable something like this that works
  # validates :recipe, :presence => true
  # validates :food, :presence => true
  validates :amount, :presence => true, :unit => true
  validates :sort_order, :presence => true, :numericality => true
  default_scope :order => "sort_order"
  
  def scale(scaling_factor)
    self.amount = self.amount.unit * scaling_factor
    return self
  end
  
  def cost
    return food.cost(self.amount)
  end
  
  def self.empty
    i = Ingredient.new
    i.food = Food.new
    return i
  end
end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController
  before_filter :authenticate_user!
  
  def index
    @recipe = Recipe.find(params[:recipe_id])
    if @recipe
      @ingredients = @recipe.ingredients
    else
      @ingredients = Ingredient.all
    end      
  end
  
  def show
    @ingredient = Ingredient.find(params[:id])
  end
  
  def new
    @recipe = Recipe.find(params[:recipe_id])
    @ingredient = Ingredient.new
  end
  
  def create
    @recipe = Recipe.find(params[:recipe_id])
    @ingredient = Ingredient.new(params[:ingredient])
    @ingredient.recipe = @recipe
    if @ingredient.save
      flash[:notice] = "Successfully created ingredient."
      redirect_to @ingredient
    else
      render :action => 'new'
    end
  end
  
  def edit
    @ingredient = Ingredient.find(params[:id])
  end
  
  def update
    @ingredient = Ingredient.find(params[:id])
    if @ingredient.update_attributes(params[:ingredient])
      flash[:notice] = "Successfully updated ingredient."
      redirect_to @ingredient
    else
      render :action => 'edit'
    end
  end
  
  def destroy
    @ingredient = Ingredient.find(params[:id])
    @ingredient.destroy
    flash[:notice] = "Successfully destroyed ingredient."
    redirect_to recipe_ingredients_url(@ingredient.recipe)
  end
end

app/helpers/ingredients_helper.rb
module IngredientsHelper
end

app/views/ingredients/_form.html.haml
= form_for [@recipe, @ingredient] do |f|
  = f.error_messages
  - if @ingredient.food
    %p
      @ingredient.food.name
  %p
    = f.label :sort_order
    %br/
    = f.text_field :sort_order
  %p
    = f.label :amount
    %br/
    = f.text_field :amount
  %p= f.submit

app/views/ingredients/edit.html.haml
- title "Edit Ingredient"
= render 'form'
%p
  = link_to "Show", @ingredient
  |
  \#{link_to "View All", recipe_ingredients_path(@ingredient.recipe)}

app/views/ingredients/index.html.haml
- title "Ingredients"
%table
  %tr
    %th Name
    %th Sort Order
    %th Amount
  - for ingredient in @ingredients
    %tr
      %td= ingredient.name
      %td= ingredient.sort_order
      %td= ingredient.amount
      %td= link_to "Show", ingredient
      %td= link_to "Edit", edit_ingredient_path(ingredient)
      %td= link_to "Destroy", ingredient, :confirm => 'Are you sure?', :method => :delete
%p= link_to "New Ingredient", new_recipe_ingredient_path(@recipe)

app/views/ingredients/new.html.haml
- title "New Ingredient"
= render 'form'
%p= link_to "Back to List", recipe_ingredients_path(@recipe)

app/views/ingredients/show.html.haml
- title "Ingredient"
%p
  %strong Name:
  = @ingredient.food.name
%p
  %strong Recipe:
  = link_to @ingredient.recipe.name, @ingredient.recipe
%p
  %strong Sort Order:
  = @ingredient.sort_order
%p
  %strong Amount:
  = @ingredient.amount.try_unit
%p
  = link_to "Edit", edit_ingredient_path(@ingredient)
  |
  \#{link_to "Destroy", @ingredient, :confirm => 'Are you sure?', :method => :delete} |
  \#{link_to "View All", recipe_ingredients_path(@ingredient.recipe)}